# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
      
    working_directory: ~/repo

    environment:
      TEST_REPORTS: /tmp/test-reports

    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-

      - run:
          name: Install dependencies
          command: pipenv sync --dev

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

      - run:
          name: Run tests
          command: |
            pipenv run pytest \
              --junitxml=${TEST_REPORTS}/pytest/results.xml \
              --cov ticket_universe --cov-report xml:${TEST_REPORTS}/pytest/coverage.xml

      - store_test_results:
          path: /tmp/test-reports

      - store_artifacts:
          path: /tmp/test-reports
